'use client';

import { useEffect, useState } from 'react';
import { AuthControls, type GitHubRepo } from './components/AuthControls';
import { CheckCircle2, ChevronDown, Code2, FileArchive, FileCode2, GitBranch, History, ImagePlus, LayoutDashboard, Mic, Paperclip, Plus, Search, Send, Settings2, ShieldCheck, Sparkles, UploadCloud, WandSparkles, X } from 'lucide-react';

const nav = [{ label: 'Workspace', icon: LayoutDashboard }, { label: 'Projects', icon: FileCode2 }, { label: 'Analyses', icon: Sparkles }, { label: 'Connectors', icon: GitBranch }];
type Conversation = { id: string; prompt: string; response: string; updatedAt: number; repository?: string };
const historyKey = 'devdesk-local-conversations-v1'; const selectedRepoKey = 'devdesk-selected-repository-v1';

export default function Home() {
  const [active, setActive] = useState('Workspace'); const [prompt, setPrompt] = useState(''); const [thinking, setThinking] = useState(false); const [showUpload, setShowUpload] = useState(false);
  const [message, setMessage] = useState(''); const [aiResponse, setAiResponse] = useState(''); const [chatError, setChatError] = useState(''); const [conversations, setConversations] = useState<Conversation[]>([]);
  const [activeConversationId, setActiveConversationId] = useState<string>(); const [historyOpen, setHistoryOpen] = useState(false); const [selectedRepo, setSelectedRepo] = useState<GitHubRepo>();

  useEffect(() => { try { const savedHistory = window.localStorage.getItem(historyKey); const savedRepository = window.localStorage.getItem(selectedRepoKey); if (savedHistory) setConversations(JSON.parse(savedHistory) as Conversation[]); if (savedRepository) setSelectedRepo(JSON.parse(savedRepository) as GitHubRepo); } catch { setConversations([]); } }, []);
  function chooseRepo(repo: GitHubRepo) { setSelectedRepo(repo); window.localStorage.setItem(selectedRepoKey, JSON.stringify(repo)); setMessage(''); setAiResponse(''); setChatError(''); setActiveConversationId(undefined); setHistoryOpen(false); }
  function saveConversation(nextPrompt: string, nextResponse: string) { const id = activeConversationId ?? crypto.randomUUID(); const entry = { id, prompt: nextPrompt, response: nextResponse, updatedAt: Date.now(), repository: selectedRepo?.fullName }; setActiveConversationId(id); setConversations((previous) => { const next = [entry, ...previous.filter((conversation) => conversation.id !== id)].slice(0, 8); window.localStorage.setItem(historyKey, JSON.stringify(next)); return next; }); }
  async function sendPrompt() { if (!prompt.trim() || thinking) return; const nextMessage = prompt.trim(); setThinking(true); setChatError(''); setMessage(nextMessage); setAiResponse(''); setPrompt(''); try { const content = selectedRepo ? `Repository selected: ${selectedRepo.fullName} (${selectedRepo.defaultBranch}). The repository source has not been imported yet, so do not claim you inspected its files. User question: ${nextMessage}` : nextMessage; const response = await fetch('/api/chat', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ messages: [{ role: 'user', content }] }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? 'The AI could not respond.'); setAiResponse(payload.text); saveConversation(nextMessage, payload.text); } catch (issue) { setChatError(issue instanceof Error ? issue.message : 'The AI could not respond.'); } finally { setThinking(false); } }
  function startNewChat() { setMessage(''); setAiResponse(''); setChatError(''); setPrompt(''); setActiveConversationId(undefined); setHistoryOpen(false); window.setTimeout(() => document.getElementById('chat-composer')?.focus(), 0); }
  function openConversation(conversation: Conversation) { setActiveConversationId(conversation.id); setMessage(conversation.prompt); setAiResponse(conversation.response); setChatError(''); setHistoryOpen(false); }
  const workspaceTitle = selectedRepo ? selectedRepo.name : 'No project selected'; const chatTitle = message ? message.slice(0, 34) + (message.length > 34 ? '…' : '') : 'New conversation';

  return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={16} /></div><div><strong>DevDesk</strong><span>AI code intelligence</span></div></div><button className="new-project" onClick={() => setShowUpload(true)}><Plus size={16} /> Add project</button><nav className="side-nav">{nav.map(({ label, icon: Icon }) => <button key={label} className={active === label ? 'active' : ''} onClick={() => setActive(label)}><Icon size={16} /> {label}</button>)}</nav><div className="sidebar-bottom"><div className="secure-note"><ShieldCheck size={15} /><span>Private by design<br /><small>Server-side AI boundary</small></span></div><button className="profile"><span className="avatar">A</span><span><b>Abbas Hussain</b><small>Developer</small></span><Settings2 size={15} /></button></div></aside>
    <section className="workspace"><header className="topbar"><div className="mobile-brand"><Sparkles size={16} /> DEV DESK</div><div className="project-switcher"><span className={selectedRepo ? 'project-dot' : 'project-dot muted-dot'} /> {selectedRepo ? `${selectedRepo.name} / ${selectedRepo.defaultBranch}` : 'Choose a real project'} <ChevronDown size={14} /></div><div className="top-actions"><button aria-label="Search"><Search size={17} /></button><button aria-label="Settings"><Settings2 size={17} /></button><span className="online"><i /> AI online</span><AuthControls onRepositorySelected={chooseRepo} /></div></header>
      <div className="workspace-grid"><section className="chat-column"><div className="eyebrow">DEV DESK · {selectedRepo ? 'REPOSITORY CHAT' : 'REAL WORKSPACE'}</div><h1>{selectedRepo ? `Chat about ${selectedRepo.name}.` : 'Start with a real project.'}</h1><p className="lede">{selectedRepo ? `${selectedRepo.fullName} is selected. Its source has not been analyzed yet, so DevDesk will never pretend it has read files it has not received.` : 'Choose a connected GitHub repository or add project files. Nothing shown here is demo data.'}</p>
        <div className={selectedRepo ? 'real-project-card selected-project-card' : 'real-project-card'}>{selectedRepo ? <><span className="strip-icon"><GitBranch size={15} /></span><span><b>{selectedRepo.fullName}</b><small>{selectedRepo.private ? 'Private repository' : 'Public repository'} · {selectedRepo.defaultBranch}</small></span><a href={selectedRepo.url} target="_blank" rel="noreferrer">Open GitHub</a></> : <><span className="strip-icon"><Code2 size={15} /></span><span><b>No project loaded</b><small>Use Connected in the header to choose one of your real repositories.</small></span></>}</div>
        <div className="conversation-bar"><div><span className="conversation-label"><History size={14} /> CURRENT CHAT</span><b>{chatTitle}</b><small>Messages are saved privately on this device.</small></div><div className="conversation-actions"><button onClick={() => setHistoryOpen((isOpen) => !isOpen)}><History size={14} /> History{conversations.length ? ` (${conversations.length})` : ''}</button><button className="new-chat-button" onClick={startNewChat}><Plus size={14} /> New chat</button></div></div>
        {historyOpen && <div className="history-panel"><div className="history-head"><span><History size={14} /> Recent chats</span><small>Saved on this device</small></div>{conversations.length ? conversations.map((conversation) => <button className={conversation.id === activeConversationId ? 'history-item active-history-item' : 'history-item'} key={conversation.id} onClick={() => openConversation(conversation)}><b>{conversation.prompt}</b><small>{conversation.repository ?? 'General chat'} · {new Date(conversation.updatedAt).toLocaleString()}</small></button>) : <p className="history-empty">No saved chats yet. Start with a real question below.</p>}</div>}
        <div className="chat-thread">{!message && !thinking && !aiResponse ? <div className="empty-chat"><span className="empty-chat-icon"><Sparkles size={18} /></span><div><b>{selectedRepo ? 'Repository selected — analysis has not started' : 'Your workspace is empty'}</b><p>{selectedRepo ? 'Ask a general question or add source files when you want DevDesk to perform a real codebase analysis.' : 'Tap Connected in the top bar and choose a real repository. You can also add project files when upload processing is enabled.'}</p></div></div> : <><div className="message user-message"><span className="message-avatar user-avatar">A</span><div><small>YOU · JUST NOW</small><p>{message}</p></div></div>{(aiResponse || thinking || chatError) && <div className="message ai-message"><span className="message-avatar ai-avatar"><Sparkles size={14} /></span><div><small>DEV DESK · AI RESPONSE</small>{aiResponse && <p>{aiResponse}</p>}{chatError && <p className="chat-error">{chatError}</p>}</div></div>}</>}{thinking && <div className="thinking"><span><i /><i /><i /></span> DevDesk is preparing a response...</div>}</div>
        <div className="composer-wrap"><div className="composer-tools"><button onClick={() => setShowUpload(true)}><Paperclip size={15} /> Add project</button><button disabled><Mic size={15} /> Voice soon</button><button className="send-button" onClick={sendPrompt} disabled={thinking} aria-label="Send message"><Send size={16} /></button></div><textarea id="chat-composer" value={prompt} onChange={(event) => setPrompt(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void sendPrompt(); } }} placeholder={selectedRepo ? `Ask a general question about ${selectedRepo.name}…` : 'Ask DevDesk a development question…'} rows={2} /><div className="composer-footer"><span><WandSparkles size={13} /> Source context is only used after real import</span><small>Enter to send · Shift + Enter for a new line</small></div></div></section>
        <aside className="inspector"><div className="inspector-head"><div><span className="eyebrow">PROJECT STATUS</span><h2>{workspaceTitle}</h2></div></div><div className="truth-card"><span className={selectedRepo ? 'truth-icon active-truth-icon' : 'truth-icon'}>{selectedRepo ? <CheckCircle2 size={18} /> : <GitBranch size={18} />}</span><div><b>{selectedRepo ? 'Repository selected' : 'No fabricated project data'}</b><p>{selectedRepo ? 'Repository metadata is live. Source files, analysis findings, health scores, and previews will appear only after their real workflows run.' : 'Select a real GitHub repository before DevDesk displays project details, analysis, files, or a code preview.'}</p></div></div><div className="inspector-section"><div className="section-title"><span>Analysis</span><small>Not started</small></div><div className="empty-inspector-row"><Sparkles size={15} /><span>No real analysis has been run for this project.</span></div></div><div className="inspector-section"><div className="section-title"><span>Project files</span><small>Not imported</small></div><div className="empty-inspector-row"><FileArchive size={15} /><span>Files will be listed only after an actual upload or import completes.</span></div></div><div className="preview-card"><div className="section-title"><span>Code preview</span><small>Unavailable</small></div><div className="preview-paused"><Code2 size={14} /> No source file selected</div></div></aside></div></section>
    {showUpload && <div className="modal-backdrop" onClick={() => setShowUpload(false)}><div className="upload-modal" onClick={(event) => event.stopPropagation()}><button className="close-modal" onClick={() => setShowUpload(false)}><X size={17} /></button><span className="eyebrow">REAL PROJECT WORKSPACE</span><h2>Add your codebase.</h2><p>DevDesk does not create sample projects. Choose one of your real GitHub repositories from the green Connected button in the header. File-upload and source-import workflows will appear here only when they are genuinely available.</p><div className="upload-grid"><button onClick={() => setShowUpload(false)}><GitBranch size={21} /><b>Choose GitHub repo</b><small>Close this panel, then tap Connected in the header</small></button><button disabled><UploadCloud size={21} /><b>Upload project</b><small>Not enabled yet — no fake upload state</small></button><button disabled><ImagePlus size={21} /><b>Attach files</b><small>Not enabled yet — no fake file list</small></button></div></div></div>}</main>;
}
